"""add_phase_fields_and_models

Revision ID: 995311551491
Revises: 0001_initial_schema
Create Date: 2026-08-27 06:43:13.041186

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '995311551491'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=False),
    sa.Column('code_version', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('embedding_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('configuration_snapshot', sa.JSON(), nullable=False),
    sa.Column('metrics_summary', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('replay_scenarios',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scenario_type', sa.String(length=64), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_story_id', sa.String(length=64), nullable=True),
    sa.Column('expected_outcome', sa.String(length=64), nullable=False),
    sa.Column('target_milestone', sa.String(length=64), nullable=False),
    sa.Column('target_milestone_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('replay_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('event_order', sa.Integer(), nullable=False),
    sa.Column('original_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('is_syndicated_copy', sa.Boolean(), nullable=False),
    sa.Column('syndication_origin', sa.String(length=255), nullable=True),
    sa.Column('is_load_bearing_contradiction', sa.Boolean(), nullable=False),
    sa.Column('expected_relevance', sa.String(length=100), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['replay_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replay_events_scenario_id'), 'replay_events', ['scenario_id'], unique=False)
    op.create_table('replay_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('event_order', sa.Integer(), nullable=False),
    sa.Column('replay_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('story_id', sa.String(length=64), nullable=True),
    sa.Column('story_title', sa.String(length=500), nullable=True),
    sa.Column('story_state', sa.String(length=64), nullable=False),
    sa.Column('formation_score', sa.Float(), nullable=False),
    sa.Column('independent_sources_count', sa.Integer(), nullable=False),
    sa.Column('total_articles_count', sa.Integer(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('contradiction_status', sa.String(length=50), nullable=False),
    sa.Column('is_prediction_blocked', sa.Boolean(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('impact', sa.Float(), nullable=False),
    sa.Column('urgency', sa.Float(), nullable=False),
    sa.Column('trajectory_stage', sa.String(length=50), nullable=False),
    sa.Column('alert_fired', sa.Boolean(), nullable=False),
    sa.Column('is_valid_early_alert', sa.Boolean(), nullable=False),
    sa.Column('evidence_available', sa.Boolean(), nullable=False),
    sa.Column('ranking_score', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['replay_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replay_snapshots_scenario_id'), 'replay_snapshots', ['scenario_id'], unique=False)
    op.create_table('story_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_notes_story_id'), 'story_notes', ['story_id'], unique=False)
    op.create_index(op.f('ix_story_notes_user_id'), 'story_notes', ['user_id'], unique=False)
    op.add_column('alerts', sa.Column('alert_type', sa.String(length=50), nullable=False))
    op.add_column('alerts', sa.Column('headline_in_progress', sa.String(length=500), nullable=True))
    op.add_column('alerts', sa.Column('impact_level', sa.String(length=20), nullable=False))
    op.add_column('alerts', sa.Column('ranking_score', sa.Float(), nullable=False))
    op.add_column('alerts', sa.Column('ranking_explanation', sa.Text(), nullable=True))
    op.add_column('alerts', sa.Column('formation_score', sa.Float(), nullable=False))
    op.add_column('alerts', sa.Column('independent_source_count', sa.Integer(), nullable=False))
    op.add_column('alerts', sa.Column('language_count', sa.Integer(), nullable=False))
    op.add_column('alerts', sa.Column('evidence_chain_id', sa.String(length=36), nullable=True))
    op.add_column('alerts', sa.Column('evidence_available', sa.Boolean(), nullable=False))
    op.add_column('alerts', sa.Column('contradiction_status', sa.String(length=50), nullable=False))
    op.add_column('alerts', sa.Column('prediction_status', sa.String(length=50), nullable=False))
    op.alter_column('alerts', 'urgency',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('alerts', 'probability',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('alerts', 'impact',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('alerts', 'rank_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('alerts', 'formation_confidence',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('alerts', 'independent_sources_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('alerts', 'has_unresolved_contradictions',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('alerts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_alerts_rank_score'), table_name='alerts')
    op.create_index(op.f('ix_alerts_ranking_score'), 'alerts', ['ranking_score'], unique=False)
    op.alter_column('articles', 'is_original_reporting',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claims', 'is_load_bearing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claims', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('claims', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('contradictions', 'is_load_bearing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('contradictions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('contradictions', 'severity',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('contradictions', 'halted_prediction',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('events', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('evidence_chains', sa.Column('items', sa.JSON(), nullable=False))
    op.add_column('evidence_chains', sa.Column('chain_status', sa.String(length=50), nullable=False))
    op.add_column('evidence_chains', sa.Column('evidence_types_present', sa.JSON(), nullable=False))
    op.alter_column('evidence_chains', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('evidence_chains', 'step_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('evidence_chains', 'evidence_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('evidence_chains', 'claim_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('evidence_chains', 'corroborating_sources_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_evidence_chains_step_order'), table_name='evidence_chains')
    op.create_index(op.f('ix_evidence_chains_chain_status'), 'evidence_chains', ['chain_status'], unique=False)
    op.alter_column('feedbacks', 'is_positive',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('feedbacks', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('feedbacks', 'feedback_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('graph_edges', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('media_extractions', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('predictions', sa.Column('formation_probability', sa.Float(), nullable=False))
    op.add_column('predictions', sa.Column('impact_score', sa.Float(), nullable=False))
    op.add_column('predictions', sa.Column('impact_level', sa.String(length=20), nullable=False))
    op.add_column('predictions', sa.Column('current_stage', sa.String(length=50), nullable=False))
    op.add_column('predictions', sa.Column('predicted_next_stage', sa.String(length=50), nullable=False))
    op.add_column('predictions', sa.Column('trajectory_confidence', sa.Float(), nullable=False))
    op.add_column('predictions', sa.Column('trajectory_reasoning', sa.Text(), nullable=True))
    op.add_column('predictions', sa.Column('prediction_status', sa.String(length=50), nullable=False))
    op.add_column('predictions', sa.Column('blocked_reason', sa.String(length=200), nullable=True))
    op.add_column('predictions', sa.Column('contradiction_id', sa.String(length=36), nullable=True))
    op.add_column('predictions', sa.Column('historical_pattern_support', sa.JSON(), nullable=False))
    op.add_column('predictions', sa.Column('model_version', sa.String(length=50), nullable=False))
    op.alter_column('predictions', 'formation_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('predictions', 'probability',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('predictions', 'impact',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('predictions', 'trajectory_stage',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('predictions', 'is_halted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('predictions', 'theoretical_framework',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_predictions_prediction_status'), 'predictions', ['prediction_status'], unique=False)
    op.drop_column('predictions', 'dimension_breakdown')
    op.add_column('source_profiles', sa.Column('relationship_classification', sa.String(length=50), nullable=False))
    op.add_column('stories', sa.Column('formation_status', sa.String(length=50), nullable=False))
    op.add_column('stories', sa.Column('independence_score', sa.Float(), nullable=False))
    op.add_column('stories', sa.Column('source_diversity_score', sa.Float(), nullable=False))
    op.add_column('stories', sa.Column('temporal_spread_score', sa.Float(), nullable=False))
    op.add_column('stories', sa.Column('entity_alignment_score', sa.Float(), nullable=False))
    op.add_column('stories', sa.Column('cross_language_score', sa.Float(), nullable=False))
    op.add_column('stories', sa.Column('evidence_strength_score', sa.Float(), nullable=False))
    op.add_column('stories', sa.Column('contradiction_status', sa.String(length=50), nullable=False))
    op.add_column('stories', sa.Column('prediction_eligible', sa.Boolean(), nullable=False))
    op.add_column('stories', sa.Column('narrative_summary', sa.Text(), nullable=True))
    op.add_column('stories', sa.Column('score_breakdown', sa.JSON(), nullable=False))
    op.alter_column('stories', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('stories', 'formation_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stories', 'independent_sources_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stories', 'total_articles_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_stories_contradiction_status'), 'stories', ['contradiction_status'], unique=False)
    op.create_index(op.f('ix_stories_formation_status'), 'stories', ['formation_status'], unique=False)
    op.create_index(op.f('ix_stories_independence_score'), 'stories', ['independence_score'], unique=False)
    op.create_index(op.f('ix_stories_prediction_eligible'), 'stories', ['prediction_eligible'], unique=False)
    op.alter_column('story_articles', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('watchlists', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watchlists', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('story_articles', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_stories_prediction_eligible'), table_name='stories')
    op.drop_index(op.f('ix_stories_independence_score'), table_name='stories')
    op.drop_index(op.f('ix_stories_formation_status'), table_name='stories')
    op.drop_index(op.f('ix_stories_contradiction_status'), table_name='stories')
    op.alter_column('stories', 'total_articles_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stories', 'independent_sources_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stories', 'formation_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stories', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('stories', 'score_breakdown')
    op.drop_column('stories', 'narrative_summary')
    op.drop_column('stories', 'prediction_eligible')
    op.drop_column('stories', 'contradiction_status')
    op.drop_column('stories', 'evidence_strength_score')
    op.drop_column('stories', 'cross_language_score')
    op.drop_column('stories', 'entity_alignment_score')
    op.drop_column('stories', 'temporal_spread_score')
    op.drop_column('stories', 'source_diversity_score')
    op.drop_column('stories', 'independence_score')
    op.drop_column('stories', 'formation_status')
    op.drop_column('source_profiles', 'relationship_classification')
    op.add_column('predictions', sa.Column('dimension_breakdown', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_predictions_prediction_status'), table_name='predictions')
    op.alter_column('predictions', 'theoretical_framework',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('predictions', 'is_halted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('predictions', 'trajectory_stage',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('predictions', 'impact',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('predictions', 'probability',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('predictions', 'formation_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('predictions', 'model_version')
    op.drop_column('predictions', 'historical_pattern_support')
    op.drop_column('predictions', 'contradiction_id')
    op.drop_column('predictions', 'blocked_reason')
    op.drop_column('predictions', 'prediction_status')
    op.drop_column('predictions', 'trajectory_reasoning')
    op.drop_column('predictions', 'trajectory_confidence')
    op.drop_column('predictions', 'predicted_next_stage')
    op.drop_column('predictions', 'current_stage')
    op.drop_column('predictions', 'impact_level')
    op.drop_column('predictions', 'impact_score')
    op.drop_column('predictions', 'formation_probability')
    op.alter_column('media_extractions', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('graph_edges', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('feedbacks', 'feedback_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('feedbacks', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('feedbacks', 'is_positive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_evidence_chains_chain_status'), table_name='evidence_chains')
    op.create_index(op.f('ix_evidence_chains_step_order'), 'evidence_chains', ['step_order'], unique=False)
    op.alter_column('evidence_chains', 'corroborating_sources_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('evidence_chains', 'claim_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('evidence_chains', 'evidence_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('evidence_chains', 'step_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('evidence_chains', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('evidence_chains', 'evidence_types_present')
    op.drop_column('evidence_chains', 'chain_status')
    op.drop_column('evidence_chains', 'items')
    op.alter_column('events', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('contradictions', 'halted_prediction',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('contradictions', 'severity',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('contradictions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('contradictions', 'is_load_bearing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claims', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('claims', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('claims', 'is_load_bearing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('articles', 'is_original_reporting',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_alerts_ranking_score'), table_name='alerts')
    op.create_index(op.f('ix_alerts_rank_score'), 'alerts', ['rank_score'], unique=False)
    op.alter_column('alerts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('alerts', 'has_unresolved_contradictions',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('alerts', 'independent_sources_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('alerts', 'formation_confidence',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('alerts', 'rank_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('alerts', 'impact',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('alerts', 'probability',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('alerts', 'urgency',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('alerts', 'prediction_status')
    op.drop_column('alerts', 'contradiction_status')
    op.drop_column('alerts', 'evidence_available')
    op.drop_column('alerts', 'evidence_chain_id')
    op.drop_column('alerts', 'language_count')
    op.drop_column('alerts', 'independent_source_count')
    op.drop_column('alerts', 'formation_score')
    op.drop_column('alerts', 'ranking_explanation')
    op.drop_column('alerts', 'ranking_score')
    op.drop_column('alerts', 'impact_level')
    op.drop_column('alerts', 'headline_in_progress')
    op.drop_column('alerts', 'alert_type')
    op.drop_index(op.f('ix_story_notes_user_id'), table_name='story_notes')
    op.drop_index(op.f('ix_story_notes_story_id'), table_name='story_notes')
    op.drop_table('story_notes')
    op.drop_index(op.f('ix_replay_snapshots_scenario_id'), table_name='replay_snapshots')
    op.drop_table('replay_snapshots')
    op.drop_index(op.f('ix_replay_events_scenario_id'), table_name='replay_events')
    op.drop_table('replay_events')
    op.drop_table('replay_scenarios')
    op.drop_table('evaluation_runs')
    # ### end Alembic commands ###
